FROM node:alpine
WORKDIR /home/node/app
COPY ./server ./server
COPY ./interfaces ./interfaces
WORKDIR /home/node/app/server
RUN npm install 
RUN npm run build
RUN npm prune --production
ENV NODE_ENV production
CMD npm start
EXPOSE 80